/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Panel_AP;

/**
 *
 * @author ACER
 */
public class AP_Pasien extends javax.swing.JPanel {

    /**
     * Creates new form P_Pasien
     */
    public AP_Pasien() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound1 = new Costum.PanelRound();
        buttonDesign1 = new Costum.ButtonDesign();
        buttonDesign2 = new Costum.ButtonDesign();

        setBackground(new java.awt.Color(239, 242, 251));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound1.setBackground(new java.awt.Color(255, 255, 255));
        panelRound1.setRoundBottomLeft(50);
        panelRound1.setRoundBottomRight(50);
        panelRound1.setRoundTopLeft(50);
        panelRound1.setRoundTopRight(50);

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );

        add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 900, 350));

        buttonDesign1.setBackground(new java.awt.Color(0, 204, 102));
        buttonDesign1.setText("Tambah");
        add(buttonDesign1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 110, 30));

        buttonDesign2.setText("Cetak Bukti");
        add(buttonDesign2, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 420, 110, 30));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Costum.ButtonDesign buttonDesign1;
    private Costum.ButtonDesign buttonDesign2;
    private Costum.PanelRound panelRound1;
    // End of variables declaration//GEN-END:variables
}
